### ISSUE TITLE
getMonthlyMenu, getMonthlySchedule 오류

### ISSUE THREAD

**Issue by Indvel** [agemor/school-api#3]
위 두개의 메소드 사용 시
"error: unreported exception SchoolException; must be caught or declared to be thrown"
또는
"Unhandled exception: org.hyunjun.school.SchoolException"
이라는 오류가 납니다...
학교 구분, 지역 구분, 학교 코드도 알맞게 썼습니다.

**Comment by agemor** [comment]
서버 오류, 교육청 홈페이지 구조 변경 등으로 발생할 수 있는 예외 상황 처리를 위해 예외 핸들러를 구현하도록 해 두었습니다. 아래와 같이 try-catch 문으로 감싸 주시면 됩니다.

```
try {
   /** 코드 ***/
} catch (SchoolException e) {
}
```

**Comment by agemor** [comment]
예외 핸들러 구현을 강제한 것을 README에는 반영하지 못했네요. 업데이트하겠습니다.

**Comment by Indvel** [comment]
답변 감사합니다!

2016. 11. 8. 오후 12:18에 "HyunJun Kim" <notifications@github.com>님이 작성:

**Comment by Indvel** [comment]
"Unreachable catch block for SchoolException. This exception is never
thrown from the try statement body" 라는 오류가 납니다.
그래서 try 안에 throw를 넣어줬더니 getMonthly~ 부분에서 Unreachable statement 오류가 나네요...ㅜ

2016년 11월 8일 오후 12:18, HyunJun Kim <notifications@github.com>님이 작성:
