### ISSUE TITLE
급식 정보를 불러오려고 하는데 모두 없다고 나오네요

### ISSUE THREAD

**Issue by malloc099** [agemor/school-api#4]
"급식이 없습니다"

급식이 나오는 날에도 저런 결과만 계속 나와서 당황스럽네요. 확인 부탁드립니다.

**Comment by malloc099** [comment]
![default](https://cloud.githubusercontent.com/assets/7106939/21427620/eb9fc6f0-c898-11e6-9ef2-2afefdf87329.PNG)

**Comment by agemor** [comment]
확인 결과 서버 데이터 전송과 파싱에는 문제가 없는 듯 합니다.

다만 올려주신 해당하는 일자 (2016년 12월 21일)의 대기고등학교 급식 정보에는 교육청 서버에 급식 데이터가 등록되어 있지 않습니다. (아래 이미지 참고)

![result](https://cloud.githubusercontent.com/assets/6297755/21446344/5285bc7a-c908-11e6-87c1-abb60b0ede43.png)
